services:

  postgres:
    image: postgres:15-alpine
    container_name: 'postgres_db'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product_service:
    build: ./services/product_service
    container_name: product_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./services/product_service:/app
    ports:
      - "8001:8001"
      - "5555:5555"  # ZMQ PUB — accessible par les subscribers
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-app_db}
      - ZMQ_PUB_PORT=5555
    depends_on:
      - postgres

  pricing_service:
    build: ./services/pricing_service
    container_name: pricing_service
    command: python main.py
    volumes:
      - ./services/pricing_service:/app
    ports:
      - "5556:5556"  # ZMQ REP — accessible par le client REQ de la gateway
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-app_db}
      - PRODUCT_ZMQ_URL=tcp://product_service:5555
      - PRICING_REP_PORT=5556
      - PRODUCT_SERVICE_URL=http://product_service:8001
    depends_on:
      - postgres
      - product_service

  gateway_service:
    build: ./services/gateway_service
    container_name: gateway_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/gateway_service:/app
    ports:
      - "8000:8000"
    environment:
      - PRODUCT_SERVICE_URL=http://product_service:8001
      - PRICING_ZMQ_URL=tcp://pricing_service:5556
    depends_on:
      - product_service
      - pricing_service

volumes:
  postgres_data:
