services:

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: 'rabbitmq_api_client'
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-password}
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:15-alpine
    container_name: 'postgres_db'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product_service:
    build: ./services/product_service
    container_name: product_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/product_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
